### ISSUE TITLE
ElementUI のフォントが不足している

### ISSUE THREAD

**Issue by ptr-tsukuyomi** [umineko1996/voicebutton#5]
ElementUI 用のフォントが存在しないため、ドロップダウンリストの右側がいわゆる豆腐になっていると思います。

![コメント 2020-04-12 213233](https://user-images.githubusercontent.com/3198910/79068890-34101880-7d05-11ea-90af-5212e299d348.png)

ElementUI 用のフォントは公式サイトでテーマを作成すると入手することができます。
https://element.eleme.io/#/en-US/theme

テーマを作成した後、右上のDownloadボタンを押すと、zipファイルをダウンロードすることができます。
zipファイルを開くと、themeディレクトリの中にフォントが入ったfontsディレクトリがあります。
このディレクトリを`index.html`と同じ場所に配置すると、ページの読み込み時に自動的にロードされると思います。

なお、themeディレクトリの中にある`index.css`を`index.html`と同じ場所にあるものと差し替えると、作成したテーマを適用することができます。

**Comment by ptr-tsukuyomi** [comment]
間違って本文無しで投稿したため一度閉じました。
失礼しました。

**Comment by umineko1996** [comment]
最新のelement-uiパッケージのfontファイルはさし変わっているらしく、v2.7.2以前のものを使用することで、文字化けせずに表示されるようになりました。
https://unpkg.com/browse/element-ui@2.7.2/packages/theme-chalk/lib/fonts/

**Comment by ptr-tsukuyomi** [comment]
確認してから書けばよかったですね、すいません。

兎鞠まりボタンのフォントを、新たに生成したzipファイルのものに差し替えたところ、こちらでも化けました。
ただ、`index.css`も同時に差し替えると、正しく表示されるようになりました。

どうやら`index.css`とフォントは、同じzipファイルに入っているものを使用する必要があるようです。

**Comment by umineko1996** [comment]
わざわざご確認いただいてありがとうございます。
`index.css`含めての差し替えもローカルで何度か試したのですが、キャッシュが残っていたせいか化けたままになってしまっていたので、cssは関係ない問題なのかと勘違いしておりました。

本当に助かります！
